<?php

namespace Tests\Feature\Http;

use App\Models\PeriodeAkademik;
use App\Models\Prodi;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Http;
use Tests\Feature\SeedOnce;
use Tests\TestCase;

class GeneratorControllerTest extends TestCase
{
    use RefreshDatabase, SeedOnce;

    protected function setUp(): void
    {
        parent::setUp();
        $this->seedOnce();
    }

    public function test_unauthenticated_user_redirected_from_index(): void
    {
        $response = $this->get(route('generator'));
        $response->assertStatus(302);
    }

    public function test_unauthorized_user_gets_403(): void
    {
        $user = User::factory()->create(['is_active' => true]);
        $response = $this->actingAs($user)->get(route('generator'));
        $response->assertStatus(403);
    }

    public function test_index_shows_generator_page_for_authorized_user(): void
    {
        Prodi::factory()->create();
        PeriodeAkademik::factory()->create();

        $response = $this->actingAs($this->admin())->get(route('generator'));
        $response->assertStatus(200);
        $response->assertInertia(fn ($page) => $page->component('Generator/Index'));
    }

    public function test_generate_calls_generator_document_agent(): void
    {
        Prodi::factory()->create();
        PeriodeAkademik::factory()->create();

        Http::fake([
            '*/mcp/tools/call' => Http::response(['task_id' => 'test-123'], 200),
            '*/mcp/tasks/test-123' => Http::response([
                'status' => 'completed',
                'result' => [
                    'narasi' => 'Test narrative generated by Gemini LLM',
                    'sections' => [
                        ['judul' => 'Cover', 'isi' => 'Test cover'],
                        ['judul' => 'Pendahuluan', 'isi' => 'Test introduction'],
                    ],
                    'jenis_dokumen' => 'LED',
                    'prodi' => 'Test Prodi',
                    'periode' => 'Test Periode',
                    'file_path' => '/path/to/generated/document.docx',
                ],
            ], 200),
        ]);

        $response = $this->actingAs($this->admin())->from(route('generator'))->post(route('generator.generate'), [
            'prodi_id' => 1,
            'periode_id' => 1,
            'jenis_dokumen' => 'led',
        ]);

        $response->assertStatus(302);
        $response->assertRedirect(route('generator'));

        // Get session data
        $sessionData = session()->all();

        // Check for error first
        if (isset($sessionData['error']) && ! empty($sessionData['error'])) {
            $this->fail('Session has error: '.$sessionData['error']);
        }

        $this->assertTrue(isset($sessionData['success']) && ! empty($sessionData['success']), 'Expected success flash message not found.');
    }
}
